version: '3.8'

services:
  test_backend:
    build: .
    container_name: quote-service
    ports:
      - '8080:8080'
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - test-network

  postgres:
    image: postgres:14
    env_file:
      - .env
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  test-network:
    driver: bridge